spring.application.name=registrationjwt

spring.datasource.url=jdbc:mysql://localhost:3306/regsjwt
spring.datasource.username=****
spring.datasource.password=******
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.key=*******************
jwt.expiry=8640000
jwt.issuer=*************